services:
  - type: web
    name: secure-chat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --timeout 120 main:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 1